using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnityLuaSystem.SourceGenerator {
    /// <summary>
    /// Luaモジュールの型付き呼び出しコードを生成するSource Generator
    /// </summary>
    [Generator]
    public sealed class LuaBindingSourceGenerator : ISourceGenerator {
        private const string FunctionAttributeName = "UnityLuaSystem.LuaFunctionAttribute";
        private const string ModuleAttributeName = "UnityLuaSystem.LuaModuleAttribute";
        private const string ObjectAttributeName = "UnityLuaSystem.LuaObjectAttribute";

        /// <inheritdoc/>
        public void Initialize(GeneratorInitializationContext context) {
            context.RegisterForSyntaxNotifications(() => new ModuleSyntaxReceiver());
        }

        /// <inheritdoc/>
        public void Execute(GeneratorExecutionContext context) {
            if (!(context.SyntaxReceiver is ModuleSyntaxReceiver receiver)) {
                return;
            }

            var processedTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var declaration in receiver.Candidates) {
                var semanticModel = context.Compilation.GetSemanticModel(declaration.SyntaxTree);
                if (!(semanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol moduleType)) {
                    continue;
                }
                if (!processedTypes.Add(moduleType) || GetAttribute(moduleType, ModuleAttributeName) == null) {
                    continue;
                }
                if (moduleType.ContainingType != null || moduleType.IsGenericType) {
                    continue;
                }

                var source = GenerateBinding(moduleType);
                if (source != null) {
                    var hintName = moduleType.ToDisplayString().Replace('.', '_').Replace('+', '_');
                    context.AddSource($"{hintName}.UnityLuaSystem.Binding.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            }
        }

        /// <summary>
        /// モジュール型の生成済みバインディングコードを構築
        /// </summary>
        /// <param name="moduleType">生成対象のモジュール型</param>
        /// <returns>生成するC#コード、またはnull</returns>
        private static string GenerateBinding(INamedTypeSymbol moduleType) {
            var attributedMethods = moduleType.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary && GetAttribute(method, FunctionAttributeName) != null)
                .ToArray();
            var duplicatedNames = new HashSet<string>(
                attributedMethods.GroupBy(method => method.Name).Where(group => group.Count() > 1).Select(group => group.Key),
                StringComparer.Ordinal);
            var methods = attributedMethods
                .Where(method => method.DeclaredAccessibility == Accessibility.Public)
                .Where(method => !method.IsGenericMethod)
                .Where(method => !duplicatedNames.Contains(method.Name))
                .Where(IsSupportedMethod)
                .ToArray();
            if (methods.Length == 0) {
                return null;
            }

            var namespaceName = moduleType.ContainingNamespace.IsGlobalNamespace
                ? null
                : moduleType.ContainingNamespace.ToDisplayString();
            var moduleTypeName = moduleType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var bindingTypeName = $"__UnityLuaSystem_{moduleType.Name}Binding";
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable disable");
            if (namespaceName != null) {
                builder.Append("namespace ").Append(namespaceName).AppendLine(" {");
            }
            builder.Append("    internal sealed class ").Append(bindingTypeName)
                .AppendLine(" : global::UnityLuaSystem.ILuaGeneratedModuleBinding {");
            if (!moduleType.IsStatic) {
                builder.Append("        private readonly ").Append(moduleTypeName).AppendLine(" _target;");
                builder.AppendLine();
            }
            builder.Append("        public global::System.Type ModuleType => typeof(").Append(moduleTypeName).AppendLine(");");
            builder.AppendLine();
            builder.Append("        public ").Append(bindingTypeName).AppendLine("(object target) {");
            if (!moduleType.IsStatic) {
                builder.Append("            _target = (").Append(moduleTypeName).AppendLine(")target;");
            }
            builder.AppendLine("        }");
            builder.AppendLine();
            AppendLookupMethod(builder, methods);
            foreach (var method in methods) {
                AppendCallback(builder, method, moduleTypeName);
            }
            builder.AppendLine("    }");
            if (namespaceName != null) {
                builder.AppendLine("}");
            }
            return builder.ToString();
        }

        /// <summary>
        /// 生成済み関数を検索する処理を構築
        /// </summary>
        private static void AppendLookupMethod(StringBuilder builder, IEnumerable<IMethodSymbol> methods) {
            builder.AppendLine("        public bool TryGetFunction(string methodName, out string functionName, out global::UnityLuaSystem.LuaGeneratedFunctionCallback callback) {");
            builder.AppendLine("            switch (methodName) {");
            foreach (var method in methods) {
                builder.Append("                case \"").Append(Escape(method.Name)).AppendLine("\":");
                builder.Append("                    functionName = \"").Append(Escape(GetLuaFunctionName(method))).AppendLine("\";");
                builder.Append("                    callback = Invoke_").Append(method.Name).AppendLine(";");
                builder.AppendLine("                    return true;");
            }
            builder.AppendLine("                default:");
            builder.AppendLine("                    functionName = null;");
            builder.AppendLine("                    callback = null;");
            builder.AppendLine("                    return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
        }

        /// <summary>
        /// C#メソッドを直接呼び出す処理を構築
        /// </summary>
        private static void AppendCallback(StringBuilder builder, IMethodSymbol method, string moduleTypeName) {
            builder.AppendLine();
            builder.Append("        private int Invoke_").Append(method.Name)
                .AppendLine("(global::UnityLuaSystem.LuaRuntime runtime, global::System.IntPtr state) {");
            builder.Append("            runtime.ValidateGeneratedArgumentCount(state, ").Append(method.Parameters.Length).AppendLine(");");
            for (var index = 0; index < method.Parameters.Length; index++) {
                var parameter = method.Parameters[index];
                var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append("            var argument").Append(index + 1)
                    .Append(" = runtime.ReadGeneratedValue<").Append(typeName).Append(">(state, ")
                    .Append(index + 1).AppendLine(");");
            }

            var target = method.IsStatic ? moduleTypeName : "_target";
            var invocation = new StringBuilder();
            invocation.Append(target).Append(".@").Append(method.Name).Append('(');
            invocation.Append(string.Join(", ", Enumerable.Range(1, method.Parameters.Length).Select(index => $"argument{index}")));
            invocation.Append(')');
            if (method.ReturnsVoid) {
                builder.Append("            ").Append(invocation).AppendLine(";");
                builder.AppendLine("            return 0;");
            }
            else {
                var returnTypeName = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append("            var result = ").Append(invocation).AppendLine(";");
                builder.Append("            runtime.PushGeneratedValue<").Append(returnTypeName).AppendLine(">(state, result);");
                builder.AppendLine("            return 1;");
            }
            builder.AppendLine("        }");
        }

        /// <summary>
        /// Source Generatorで直接呼び出せるメソッドかどうかを確認
        /// </summary>
        private static bool IsSupportedMethod(IMethodSymbol method) {
            if (method.Parameters.Any(parameter => parameter.RefKind != RefKind.None || !IsSupportedType(parameter.Type))) {
                return false;
            }
            return method.ReturnsVoid || IsSupportedType(method.ReturnType);
        }

        /// <summary>
        /// Luaとの同期変換に対応する型かどうかを確認
        /// </summary>
        private static bool IsSupportedType(ITypeSymbol type) {
            if (type is IArrayTypeSymbol arrayType) {
                return arrayType.Rank == 1 && IsSupportedType(arrayType.ElementType);
            }
            switch (type.SpecialType) {
                case SpecialType.System_Boolean:
                case SpecialType.System_Int32:
                case SpecialType.System_Int64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_String:
                    return true;
            }
            return type is INamedTypeSymbol namedType && GetAttribute(namedType, ObjectAttributeName) != null;
        }

        /// <summary>
        /// Luaへ公開する関数名を取得
        /// </summary>
        private static string GetLuaFunctionName(IMethodSymbol method) {
            var attribute = GetAttribute(method, FunctionAttributeName);
            if (attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string name && !string.IsNullOrEmpty(name)) {
                return name;
            }
            return method.Name;
        }

        /// <summary>
        /// 指定した完全名のAttributeを取得
        /// </summary>
        private static AttributeData GetAttribute(ISymbol symbol, string attributeName) {
            return symbol.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == attributeName);
        }

        /// <summary>
        /// 生成する文字列リテラルをエスケープ
        /// </summary>
        private static string Escape(string value) {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        /// <summary>
        /// Attributeを持つ可能性があるクラス宣言を収集
        /// </summary>
        private sealed class ModuleSyntaxReceiver : ISyntaxReceiver {
            /// <summary>Attributeを持つクラス宣言</summary>
            internal List<ClassDeclarationSyntax> Candidates { get; } = new List<ClassDeclarationSyntax>();

            /// <inheritdoc/>
            public void OnVisitSyntaxNode(SyntaxNode syntaxNode) {
                if (syntaxNode is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0) {
                    Candidates.Add(declaration);
                }
            }
        }
    }
}
