---@meta

-- Generated by Unity Lua System. Do not edit.

---Luaへuserdataとして公開するプレイヤーのサンプル
---@class UnityLuaSystemSamples_SamplePlayer
local __UnityLuaSystemSamples_SamplePlayer = {}
---現在の体力をLuaへ返却
---@return integer 現在の体力
function __UnityLuaSystemSamples_SamplePlayer:get_health() end
---名前をLuaへ返却
---@return string プレイヤー名
function __UnityLuaSystemSamples_SamplePlayer:get_name() end
---Luaから指定された量だけ体力を回復
---@param amount integer 回復量
---@return integer 回復後の体力
function __UnityLuaSystemSamples_SamplePlayer:heal(amount) end

---インスタンスを登録するLuaモジュールのサンプル
---@class UnityLuaSystemSamples_SampleInstanceModuleModule
---@type UnityLuaSystemSamples_SampleInstanceModuleModule
sample_instance = sample_instance or {}
---登録済みインスタンスが保持するメッセージを生成
---@param value string メッセージへ含める値
---@return string 生成したメッセージ
function sample_instance.create_message(value) end
---LuaObjectとして公開するプレイヤーを返却
---@return UnityLuaSystemSamples_SamplePlayer 登録済みのプレイヤー
function sample_instance.get_player() end
---非同期処理の完了後にLuaへ文字列を返却
---@param value string メッセージへ含める値
---@return string 非同期処理の完了後に返すメッセージ
function sample_instance.load_message_async(value) end
---UniTask処理の完了後にLuaへ文字列を返却
---@param value string メッセージへ含める値
---@return string UniTask処理の完了後に返すメッセージ
function sample_instance.load_unitask_message_async(value) end
---RuntimeのTickに合わせて利用者管理の処理を進行
function sample_instance.run_controlled_operation() end

---static関数を登録するLuaモジュールのサンプル
---@class UnityLuaSystemSamples_SampleStaticModuleModule
---@type UnityLuaSystemSamples_SampleStaticModuleModule
sample_static = sample_static or {}
---2つの整数を加算
---@param left integer 左辺の値
---@param right integer 右辺の値
---@return integer 加算結果
function sample_static.add(left, right) end
---Lua tableへ変換される整数配列を生成
---@return integer[] Lua tableへ変換する整数配列
function sample_static.create_values() end
---文字列へ接頭辞を付与
---@param value string 装飾する文字列
---@return string 接頭辞を付けた文字列
function sample_static.decorate(value) end
---Lua tableから受け取った整数配列を合計
---@param values integer[] 合計する整数配列
---@return integer 配列要素の合計
function sample_static.sum(values) end
