using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UnityLuaSystem.Editor {
    /// <summary>
    /// Source Generatorが生成したメタデータからLuaCATS定義を構築するクラス
    /// </summary>
    public static class LuaDefinitionGenerator {
        /// <summary>
        /// 生成済みLua APIメタデータからLuaCATS定義を生成
        /// </summary>
        /// <param name="metadata">定義へ含める生成済みメタデータ</param>
        /// <returns>生成したLuaCATS定義</returns>
        public static string Generate(IEnumerable<ILuaGeneratedApiMetadata> metadata) {
            if (metadata == null) {
                throw new ArgumentNullException(nameof(metadata));
            }

            var builder = new StringBuilder();
            builder.AppendLine("---@meta");
            builder.AppendLine();
            builder.AppendLine("-- Generated by Unity Lua System. Do not edit.");

            foreach (var item in metadata.Where(item => item != null).OrderBy(item => item.GetType().Assembly.FullName, StringComparer.Ordinal)) {
                if (string.IsNullOrWhiteSpace(item.Definition)) {
                    continue;
                }

                builder.AppendLine();
                builder.Append(item.Definition.TrimEnd());
                builder.AppendLine();
            }
            return builder.ToString();
        }
    }
}
